services:
  postgres:
    image: postgres:16
    container_name: vehicle-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: vehicle_db
      POSTGRES_USER: vehicle
      POSTGRES_PASSWORD: vehicle
    volumes:
      - postgres_data:/var/lib/postgresql/data

  vehicle-api:
    build: .
    container_name: vehicle-api
    restart: unless-stopped
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/vehicle_db
      SPRING_DATASOURCE_USERNAME: vehicle
      SPRING_DATASOURCE_PASSWORD: vehicle
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: https://cognito-idp.us-east-2.amazonaws.com/us-east-2_8n2LHUg3r
    ports:
      - "8080:8080"

volumes:
  postgres_data: