spring:
  application:
    name: vehicle-api

  datasource:
    url: jdbc:postgresql://localhost:5432/vehicle_db
    username: vehicle
    password: vehicle

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://cognito-idp.us-east-2.amazonaws.com/us-east-2_8n2LHUg3r

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info